# NumPy
**NumPy** is designed for Scientific computation, It is possible to generate n-dimensional array objects. (Has tools for integrating code with existing C, C+++, Fortran)

For more information: _**numpy.org**_

**Some functionalities:**
* linear algebra
* generate random numbers

**numpy array:** additional data type provided by NumPy. They are used to represent vectors and matrices, by default the elements are floating point numbers. To be easier to understand let's assume matrice as two-dimensional tables.

`import numpy as np`
adding as by the end allow us to set nicknames.
`np.zeros(x)` allow me to create vectors/matrices filled with zeros, x represent how many elements.



## Summary
1. np.zero()
    1. vector
    2. matrix
2. np.array()
    1. vector
    2. matrix
    3. transpose
    4. slicing
       1. vector
       2. matrix
            1. rows
            2. column
3. indexing
    1. copy
        1. incorrect
        2. correct
4. Building arrays
    1. np.linspace
    2. np.logspace
       1. specify logbase
    3. random arrays
5. Functions, Data Attributes

## 1. np.zero()
`np.empty` a way to use less process power, but need more care.

### Vector
`np.zero(x)` to define how many elements inside the 1d array.

In [96]:
import numpy as np
zero_vector = np.zeros(5)
print(zero_vector)

[0. 0. 0. 0. 0.]


### Matrix
`np.zero(x,y)` to define how many elements inside the 2d array.
 **x : rows**
 **y : columns**

In [97]:
import numpy as np
zero_matrix = np.zeros ((5,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## 2. np.array()
**shape** and **size** are data attribute of arrays, they do not need () like methods.

### Vector (1 Dimension)

In [98]:
import numpy as np
x = np.array([1,2,3])
y = np.array([2,4,6])
print(x)
print(y)

print(f'{x.shape}')
print(f'{x.size}')

[1 2 3]
[2 4 6]
(3,)
3


### Matrix (2 Dimension)

In [99]:
import numpy as np
z = np.array([[1,3], [5,9]])
print(z)

[[1 3]
 [5 9]]


### Transpose Matrices

In [100]:
import numpy as np
z = np.array([[1,3], [5,9]])
z1 = z.transpose()
print(z1)

[[1 5]
 [3 9]]


### Slicing

#### Vectors (1 dimension)

In [101]:
import numpy as np
x = np.array([1,2,3])
y = np.array([2,4,6])

print(x[0])
print(x[0:2])

z = x + y

print(f'{x} + {y} = {z}')


1
[1 2]
[1 2 3] + [2 4 6] = [3 6 9]


#### Matrices (2 dimensions+)

##### Columns

In [102]:
import numpy as np
x2 = np.array([[1,2,3], [4,5,6]])
y2 = np.array([[2,4,6], [8,10,12]])

print(x2[:,0])                #get all numbers from the first column
print(y2[:,0])                # get all number from the first column
print(x2[:,0] + y2[:,0])      #sum term by term of the specified columns

[1 4]
[2 8]
[ 3 12]


##### Rows

In [103]:
import numpy as np
x2 = np.array([[1,2,3], [4,5,6]])
y2 = np.array([[2,4,6], [8,10,12]])
print(x2)
print('\n')

print('test 1',x2[:2])
print('\n')
print(x2[1,:])
print('\n')
print(x2[0])          #same as before just demonstrating (less typing)
print('\n')
print(y2[0,:])
print('\n')
print(x2[0,:] + y2[1,:])


[[1 2 3]
 [4 5 6]]


test 1 [[1 2 3]
 [4 5 6]]


[4 5 6]


[1 2 3]


[2 4 6]


[ 9 12 15]


## 3. Indexing
Can use arrays or lists to do that. It is important to use it to don't create bond between...

In [104]:
import numpy as np
index_array = np.array([0,2,3])
index_list = [0,2,3]

z = np.array([1,3,5,7,9])
z1 = z + 1

print('1: ',z1[index_array]) #Both will give me the term 0,2,3 of z1
print('2: ',z1[index_list])

print('3: ',z1 > 6)    #Show True or False each term

print('4: ',z1[z1>6])

z3 = z1 > 6
z4 = np.array([8,16,32,33,0])
print('5: ',z3)

#When z3 is created it will be a boolean array, the examples bellow demonstrate that it will always show terms 3 and 4 (no matter the value there)
print('6: ',z[z3])
print('7: ',z1[z3])
print('8: ',z4[z3])


1:  [2 6 8]
2:  [2 6 8]
3:  [False False False  True  True]
4:  [ 8 10]
5:  [False False False  True  True]
6:  [7 9]
7:  [ 8 10]
8:  [33  0]


### Copying
To work with arrays it's important to note that different from lists slicing will create a bond between them, to sort it out we use INDEXING.

#### incorrectly (bonding them)

In [105]:
import numpy as np

z = np.array([1,3,5,7,9])

print(f'This is z1: {z}')

w = z[0:3]
print(f'this is w: {w}')

w[0] = 600

print(f'{z} and are bonded {w}')

This is z1: [1 3 5 7 9]
this is w: [1 3 5]
[600   3   5   7   9] and are bonded [600   3   5]


#### correctly (not bonding)

In [106]:
import numpy as np
z = np.array([1,3,5,7,9])

index_z = np.array([0,1,2])
w = z[index_z]
w[0] = 600

print(f'{z} and are bonded {w}')

[1 3 5 7 9] and are bonded [600   3   5]


## 4. Building linear arrays
to create an array linearly spaced

### np.linspace()
`np.linspace(start,stop,how many terms)`

In [107]:
import numpy as np
x = np.linspace(0,100,10)
print(x)


[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


### np.logspace()
`nplogspace(start,stop,how many terms)`

In [108]:
import numpy as np
y = np.logspace(1,2,10) #log 10 = 1, log 100 = 2 and 10 terms
print(y)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


#### Specify logbase

In [109]:
import numpy as np
print(np.logspace(np.log10(250),np.log10(500),10))

[250.         270.01493472 291.63225989 314.98026247 340.19750004
 367.43362307 396.85026299 428.62199143 462.93735614 500.        ]


### Random Arrays

In [110]:
random_np = np.random.random(10)
print(random_np)

print(np.any(random_np>0.9))
print(np.all(random_np>=0.1))

[0.59794704 0.82863358 0.28936771 0.81501657 0.98140604 0.64386048
 0.34415574 0.10205614 0.36462142 0.52099526]
True
True


## 5. Functions, Data Attributes and Methods


- np.any(array)
- np.all(array)
- np.shape
- n.size
- np.sum(array, axis = 0) Rows
- np.sum(array, axis = 1) Columns
- np.sum(array, axis = x) For 2d+ arrays


## 6. Random
`np.random.random(x)`
`np.random.normal(a,b,x))`
`np.random.randint(low, high, x)`
a = mean = 0 (usual)
b = standard deviation = 1 (normal distribution)
x = array (for more than 1d it's necessary to use x as a tuple)

### Question
What does numpy.random.random((5,2,3)) do?

Generates a 5 x 2 x 3 NumPy array with random uniform values.

### Vector

In [111]:
import numpy as np
x = np.random.random(5)
y = np.random.normal(0,1,5)
z = np.random.randint(1,7, 5)
print(x)
print(y)
print(z)

[0.51750195 0.92952066 0.50171182 0.57330992 0.68106224]
[-1.27707322 -0.80514995 -0.893356   -0.2159618   1.48372996]
[4 1 6 3 5]


### Matrix

In [112]:
import numpy as np

x = np.random.random((2,5))
y = np.random.normal(0,1, (2,5))
z = np.random.randint(1,7, (2,5))

print(x)
print('\n')
print(y)
print('\n')
print(z)

[[0.41302902 0.72397025 0.33217146 0.85261687 0.74839874]
 [0.03221615 0.08015797 0.63515839 0.3860134  0.07306959]]


[[-1.84234347  0.56314726  0.52844485 -1.32300837  0.47260376]
 [ 0.20802046  0.40219314 -0.85339577  0.5985843  -0.49294546]]


[[2 4 2 5 1]
 [1 3 4 6 2]]


#### Some Functions
`np.sum(array, axis = x)`
x = 0 (first term) = Rows
x = 1 (second term) = Columns
x = 2+ (cases of arrays with more dimensions)

In [113]:
x = np.random.randint(1,7, (3,10))
print(x)
print('array shape:', x.shape)

print('array sum:',np.sum(x))
print('rows sum:',np.sum(x, axis=0)) # sum of all rows of the array
print('columns sum:',np.sum(x, axis=1)) #2 sum of all columns array

[[1 2 1 3 1 1 6 3 4 4]
 [5 2 3 2 1 6 4 4 4 1]
 [6 1 3 1 5 2 3 1 1 2]]
array shape: (3, 10)
array sum: 83
rows sum: [12  5  7  6  7  9 13  8  9  7]
columns sum: [26 32 25]
